services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: produits

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8081:8080'

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    restart: always
    ports:
      - "8083:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produits
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres